#!/usr/bin/env python3

import rclpy

from rclpy.node import Node

from sensor_msgs.msg import JointState

import math

import time



class JointPublisher(Node):

    def __init__(self):

        super().__init__('joint_state_publisher')

        self.publisher = self.create_publisher(JointState, 'joint_states', 10)

        self.timer = self.create_timer(0.05, self.timer_callback)

        self.start_time = time.time()

        self.get_logger().info("Joint State Publisher started.")



    def timer_callback(self):

        msg = JointState()

        msg.header.stamp = self.get_clock().now().to_msg()

        msg.name = ['joint2']

        t = time.time() - self.start_time

        msg.position = [math.sin(t)]

        self.publisher.publish(msg)



def main(args=None):

    rclpy.init(args=args)

    node = JointPublisher()

    rclpy.spin(node)

    node.destroy_node()

    rclpy.shutdown()



if __name__ == '__main__':

    main()

